# Generated by Django 5.2.1 on 2025-06-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_comment='Id пользователя telegram', db_index=True, help_text='Id пользователя telegram', unique=True, verbose_name='Id пользователя telegram')),
                ('username', models.SlugField(blank=True, db_comment='Username пользователя telegram', help_text='Username пользователя telegram', null=True, verbose_name='Username пользователя telegram')),
                ('is_banned', models.BooleanField(db_comment='Флаг блокировки пользователя telegram', default=False, help_text='Флаг блокировки пользователя telegram', verbose_name='Флаг блокировки пользователя telegram')),
            ],
            options={
                'verbose_name': 'Пользователь telegram',
                'verbose_name_plural': 'Пользователи telegram',
            },
        ),
    ]
