version: '3'

volumes:
  pg_data:
  redis_data:

services:

  db:
    image: postgres:17-alpine
    env_file: .env
    restart: on-failure
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      PGUSER: ${POSTGRES_USER}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 3s
      timeout: 3s
      retries: 3
    ports:
      - ${DOCKER_COMPOSER_PORT_DB:-5432:5432}

  redis:
    image: redis:7.2-alpine
    env_file: .env
    restart: on-failure
    volumes:
      - redis_data:/root/redis
    healthcheck:
      test: ["CMD", "redis-cli", "${REDIS_PASSWORD}", "ping"]
      interval: 3s
      timeout: 3s
      retries: 3
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - ${DOCKER_COMPOSER_PORT_REDIS:-6379:6379}
