# Generated by Django 5.2.1 on 2025-05-31 11:29

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_comment='Тайтл поста', help_text='Тайтл поста', max_length=255, verbose_name='Тайтл поста')),
                ('is_published', models.BooleanField(db_comment='Флаг опубликованности', default=False, help_text='Флаг опубликованности', verbose_name='Флаг опубликованности')),
                ('text', ckeditor.fields.RichTextField(blank=True, db_comment='Текст поста', help_text='Текст поста', null=True, verbose_name='Текст поста')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='MediaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(help_text='Контент', upload_to='contents/', verbose_name='Контент')),
                ('type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео'), ('audio', 'Аудио')], default='image', help_text='Тип контента', verbose_name='Тип контента')),
                ('post', models.ForeignKey(help_text='Пост', on_delete=django.db.models.deletion.CASCADE, related_name='media_contents', to='contents.post', verbose_name='Пост')),
            ],
            options={
                'verbose_name': 'Media-контент поста',
                'verbose_name_plural': 'Media-контент постов',
            },
        ),
    ]
