# Generated by Django 5.2.1 on 2025-05-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_comment='Тайтл поста', help_text='Тайтл поста', max_length=255, unique=True, verbose_name='Тайтл поста'),
        ),
    ]
