# Generated by Django 5.2.1 on 2025-05-31 17:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='datetime_publication',
            field=models.DateTimeField(db_comment='Дата и время публикации', default=django.utils.timezone.now, help_text='Дата и время публикации', verbose_name='Дата и время публикации'),
        ),
    ]
