# Generated by Django 5.2.1 on 2025-06-06 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_post_datetime_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_comment='Тайтл типа поста', help_text='Тайтл типа поста', max_length=255, unique=True, verbose_name='Тайтл типа поста')),
                ('key', models.SlugField(db_comment='Ключ типа поста', help_text='Ключ типа поста', unique=True, verbose_name='Ключ типа поста')),
                ('time_publication', models.DateTimeField(blank=True, db_comment='Время публикации', help_text='Время публикации(если пустой, публикуется при кажом запуске cron)', null=True, verbose_name='Время публикации')),
                ('posts', models.ManyToManyField(blank=True, help_text='Посты типа постов', related_name='types', to='contents.post', verbose_name='Посты типа постов')),
            ],
            options={
                'verbose_name': 'Тип поста',
                'verbose_name_plural': 'Тип поста',
            },
        ),
    ]
