# Generated by Django 5.2.1 on 2025-06-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_remove_post_type_posttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttype',
            name='is_publish',
            field=models.BooleanField(db_comment='Флаг разрешения публикации', default=True, help_text='Флаг разрешения публикации', verbose_name='Флаг разрешения публикации'),
        ),
    ]
