# Generated by Django 5.2.1 on 2025-06-06 23:28

from django.db import migrations
from django.db.migrations.state import StateApps
from django.db.backends.postgresql.schema import DatabaseSchemaEditor

from constants.models import PostTypeEnum


POST_TYPE = {
    PostTypeEnum.POST: {'title': 'Пост', 'is_publish': True},
    PostTypeEnum.HAPPY: {'title': 'Радость', 'is_publish': True},
    PostTypeEnum.SAD: {'title': 'Грусть', 'is_publish': True},
}


def create_post_type(apps: StateApps, schema_editor: DatabaseSchemaEditor) -> None:
    PostType = apps.get_model('contents', 'PostType')
    post_types = []
    for key, data in POST_TYPE.items():
        post_types.append(
            PostType(
                title=data['title'],
                key=key,
                is_publish=data['is_publish'],
                )
        )
    PostType.objects.bulk_create(post_types)


def delete_post_type(apps: StateApps, schema_editor: DatabaseSchemaEditor) -> None:
    PostType = apps.get_model('contents', 'PostType')
    PostType.objects.filter(key__in=POST_TYPE).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_posttype_is_publish'),
    ]

    operations = [
        migrations.RunPython(
            create_post_type,
            reverse_code=delete_post_type
        ),
    ]
