# Generated by Django 5.2.1 on 2025-06-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_auto_20250607_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttype',
            name='time_publication',
            field=models.TimeField(blank=True, db_comment='Время публикации', help_text='Время публикации(если пустой, публикуется при кажом запуске cron)', null=True, verbose_name='Время публикации'),
        ),
    ]
