# Generated by Django 5.2.1 on 2025-06-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_alter_posttype_time_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttype',
            name='is_publish_by_admin',
            field=models.BooleanField(db_comment='Флаг публикации только админом', default=True, help_text='Флаг публикации только админом', verbose_name='Флаг публикации только админом'),
        ),
        migrations.AddField(
            model_name='posttype',
            name='is_publish_by_command',
            field=models.BooleanField(db_comment='Флаг публикации командой', default=False, help_text='Флаг публикации командой', verbose_name='Флаг публикации командой'),
        ),
        migrations.AlterField(
            model_name='posttype',
            name='time_publication',
            field=models.TimeField(blank=True, db_comment='Время публикации', help_text='Время публикации(если пустой, публикуется при каждом запуске cron)', null=True, verbose_name='Время публикации'),
        ),
    ]
