# Generated by Django 5.2.1 on 2025-06-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0009_posttype_is_publish_by_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttype',
            name='is_publish',
        ),
        migrations.AddField(
            model_name='posttype',
            name='is_publish_by_cron',
            field=models.BooleanField(db_comment='Флаг публикации по cron', default=True, help_text='Флаг публикации по cron', verbose_name='Флаг публикации по cron'),
        ),
    ]
