# Generated by Django 5.2.1 on 2025-06-29 16:20
from django.db import migrations
from django.db.migrations.state import StateApps
from django.db.backends.postgresql.schema import DatabaseSchemaEditor

from constants.models import PostTypeEnum


def correct_post_type(apps: StateApps, schema_editor: DatabaseSchemaEditor) -> None:
    PostType = apps.get_model('contents', 'PostType')
    post_types = []
    for post_type in PostType.objects.filter(key__in=(PostTypeEnum.HAPPY, PostTypeEnum.SAD)):
        post_type.is_publish_by_cron = False
        post_type.is_publish_by_command = True
        post_type.is_publish_by_admin = False
        post_types.append(post_type)
    PostType.objects.bulk_update(post_types, ('is_publish_by_cron', 'is_publish_by_command', 'is_publish_by_admin'))


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0010_remove_posttype_is_publish_and_more'),
    ]

    operations = [
        migrations.RunPython(correct_post_type, reverse_code=lambda *args, **kwargs: 0),
    ]
